<?xml version="1.0" encoding="UTF-8"?>
<Review id="Envoy_Display_Response">
  <ReviewIssue id="HW3JKPIK">
    <ReviewIssueMeta>
      <CreationDate format="yyyy-MM-dd :: HH:mm:ss:SSS z">2014-06-06 :: 19:11:41:804 IST</CreationDate>
      <LastModificationDate format="yyyy-MM-dd :: HH:mm:ss:SSS z">2014-06-10 :: 12:17:05:014 IST</LastModificationDate>
    </ReviewIssueMeta>
    <ReviewerId>Kapil_Ratan</ReviewerId>
    <AssignedTo>Kapil_Ratan</AssignedTo>
    <File></File>
    <Type>item.label.unset</Type>
    <Severity>item.label.unset</Severity>
    <Summary></Summary>
    <Description></Description>
    <Annotation>handleCurrencyCountrySelector |  catch (CommerceException e) { -- There is NO exception thrown or added form exception in this catch block.</Annotation>
    <Revision>added form exception  in addFormException</Revision>
    <Resolution>item.resolution.label.validNeedsfixing</Resolution>
    <Status>item.status.label.resolved</Status>
  </ReviewIssue>
  <ReviewIssue id="HW3JNSYM">
    <ReviewIssueMeta>
      <CreationDate format="yyyy-MM-dd :: HH:mm:ss:SSS z">2014-06-06 :: 19:14:06:238 IST</CreationDate>
      <LastModificationDate format="yyyy-MM-dd :: HH:mm:ss:SSS z">2014-06-10 :: 12:24:54:630 IST</LastModificationDate>
    </ReviewIssueMeta>
    <ReviewerId>Kapil_Ratan</ReviewerId>
    <AssignedTo>Kapil_Ratan</AssignedTo>
    <File></File>
    <Type>item.label.unset</Type>
    <Severity>item.label.unset</Severity>
    <Summary></Summary>
    <Description></Description>
    <Annotation>handleCurrencyCountrySelector | Why are there multiple try catch blocks , when the code can work within a single try catch.</Annotation>
    <Revision>some block used in transaction so we used multiply try case for same.</Revision>
    <Resolution>item.resolution.label.validNeedsfixing</Resolution>
    <Status>item.status.label.resolved</Status>
  </ReviewIssue>
</Review>